android.useAndroidX=true
# This newDsl flag was added by the Flutter template
android.newDsl=false
# This builtInKotlin flag was added by the Flutter template
android.builtInKotlin=false
org.gradle.jvmargs=-Xmx1024M -XX:MaxMetaspaceSize=384m -Dandroid.aapt2.daemon.timeout.secs=600
org.gradle.parallel=false
org.gradle.daemon=false
org.gradle.configureondemand=false
kotlin.incremental=false
android.aapt2FromMavenOverride=/usr/local/aapt2-wrapper/aapt2
